# Generated by Django 4.2 on 2023-11-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_department_tag_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_departments', to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_tags', to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_warehouses', to='core.company'),
            preserve_default=False,
        ),
    ]
