# Generated by Django 4.2 on 2023-11-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_company_tag_company_warehouse_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order_id',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_warehouses', to='core.warehouse'),
            preserve_default=False,
        ),
    ]
