# Generated by Django 4.2 on 2023-11-26 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='image/post')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_locations', to='base.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
