# Generated by Django 4.2 on 2023-11-28 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_status_ticket_created_at_ticket_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tickt_status', to='base.status'),
        ),
    ]
