# Generated by Django 4.2 on 2023-12-23 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickt_department', to='base.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickt_tag', to='base.tag'),
            preserve_default=False,
        ),
    ]
