# Generated by Django 4.2 on 2023-12-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_ticket_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['modified']},
        ),
    ]
