# Generated by Django 4.2 on 2023-12-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default='Open', on_delete=django.db.models.deletion.CASCADE, related_name='tickt_status', to='base.status'),
        ),
    ]
